### ISSUE TITLE
Scroll not updating

### ISSUE THREAD

**Issue by toddheslin** [greglobinski/gatsby-styled-blog-starter#5]
Great starter Greg! I'm loving the way you've put this starter together. One issue I have is that the scroll indices are not working for the main post.

E.g. in your example: https://gsbs.greglobinski.com/two-things-are-infinite/

The following return zero after scrolling:
`window.pageYOffset`
`document.documentElement.scrollTop`
`document.body.scrollTop`

Any ideas?

**Comment by greglobinski** [comment]
Hi Todd, thank you.
Yep, that's right and that's because of positioning of the containers, all of them (sidebar, main, top and bottom bars) have `position: absolute;` and `top: 0; bottom: 0;` properties, so when you're scrolling you are not scrolling a content of the window but a content of one of the containers (sidebar or main). 
I hope this will help. If not feel free to ask for details.

**Comment by toddheslin** [comment]
Got it, thanks @greglobinski 👍
