### ISSUE TITLE
Need to clear service worker storage in order to load new posts

### ISSUE THREAD

**Issue by Ecleptic** [greglobinski/gatsby-styled-blog-starter#8]
Every time I make a change, specifically when adding a blog post, I seem to have to clear site data from the service worker to load the new post. This shouldn't have been an issue. I'm deploying the site using the `npm deploy ` script to publish to github pages. 

`"deploy": "gatsby build --prefix-paths && gh-pages -d public"`

**Comment by greglobinski** [comment]
I have never used Github pages before, but I did some tests and it's because Github pages delivers all content with `cache-control:max-age=600` header, so all changes will be available 10 minutes after  deploying. 

And according to my knowledge you can't change it (the header setup). 

There is probably a workaround for this, we could setup the service workers to ask for new content every time,  despite of the cache-control header, but I can't help you with this now. 

Instead, I suggest using netlify.com.

If you are not attached to github.io domain, at netlify.com you get even better service, for free as well. The theme demo site (gsbs.greglobinski.com) is served by netlify.com with the default `cache-control:public, max-age=0, must-revalidate` headers, so all commited changes to the repository are available on the website immediately. 

I say commited not deployed, because using netlify you do not have to even deploy by hand, every commit to the remote origin could be automatically deployed to your netlify website. 

I hope it helps.

**Comment by Ecleptic** [comment]
Thanks! Sorry for bugging you on it! I'll check that out!
